import React, { useState, useEffect } from 'react';
import api from '../services/api';
import ReactMarkdown from 'react-markdown';
import AIResultDisplay from '../components/AIResultDisplay';

export default function ReportsPage() {
  const [items, setItems] = useState([]);
  const [selected, setSelected] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState(null);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [aiResult, setAiResult] = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [reportType, setReportType] = useState('enrollment');
  const [reportTrialId, setReportTrialId] = useState('');
  const [trials, setTrials] = useState([]);
  const emptyForm = { title: '', type: '', description: '', parameters: '', generatedBy: '', status: 'generated', data: '', format: 'pdf' };
  const [form, setForm] = useState(emptyForm);

  useEffect(() => { loadData(); }, []);
  const loadData = async () => {
    try {
      const [r, t] = await Promise.all([api.get('/reports'), api.get('/trials')]);
      setItems(Array.isArray(r.data) ? r.data : (r.data?.items || r.data?.data || r.data?.rows || [])); setTrials(Array.isArray(t.data) ? t.data : (t.data?.items || t.data?.data || t.data?.rows || []));
    } catch(e){} setLoading(false);
  };

  const handleSave = async () => {
    try {
      if (editing) await api.put(`/reports/${editing.id}`, form);
      else await api.post('/reports', form);
      setShowForm(false); setEditing(null); setForm(emptyForm); loadData();
    } catch(e) { alert(e.response?.data?.error || 'Error'); }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Delete this report?')) return;
    try { await api.delete(`/reports/${id}`); setSelected(null); loadData(); } catch(e) { alert('Error'); }
  };

  const handleEdit = (item) => { setEditing(item); setForm({...item}); setShowForm(true); };

  const handleAIReport = async () => {
    setAiLoading(true); setAiResult(null);
    try {
      const res = await api.post('/ai/generate-report', { reportType, trialId: reportTrialId || undefined });
      setAiResult(res.data);
    } catch(e) { setAiResult({ report: 'Error: ' + (e.response?.data?.error || e.message) }); }
    setAiLoading(false);
  };

  const filtered = items.filter(r => `${r.title} ${r.type} ${r.generatedBy}`.toLowerCase().includes(search.toLowerCase()));

  if (loading) return <div className="loading"><div className="loading-spinner"></div>Loading...</div>;

  if (selected) {
    let parsedData = null;
    try { parsedData = JSON.parse(selected.data); } catch(e) {}
    return (
      <div>
        <button className="back-btn" onClick={() => setSelected(null)}>&larr; Back</button>
        <div className="detail-panel">
          <h2>{'\u{1F4C4}'} {selected.title}</h2>
          <div className="detail-grid">
            <div className="detail-field"><label>Type</label><div className="value">{selected.type}</div></div>
            <div className="detail-field"><label>Format</label><div className="value">{selected.format}</div></div>
            <div className="detail-field"><label>Generated By</label><div className="value">{selected.generatedBy}</div></div>
            <div className="detail-field"><label>Status</label><div className="value"><span className="badge badge-success">{selected.status}</span></div></div>
            <div className="detail-field"><label>Created</label><div className="value">{new Date(selected.createdAt).toLocaleString()}</div></div>
          </div>
          <div className="detail-field" style={{marginTop: 16}}><label>Description</label><div className="value">{selected.description}</div></div>
          {parsedData && (
            <div style={{marginTop: 16, background: '#f8f9fa', padding: 16, borderRadius: 8}}>
              <label style={{fontSize: 12, fontWeight: 600, color: '#888', textTransform: 'uppercase'}}>Report Data</label>
              {Object.entries(parsedData).map(([key, val]) => (
                <div key={key} style={{display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid #eee'}}>
                  <span style={{fontWeight: 600, color: '#555'}}>{key.replace(/_/g, ' ')}</span>
                  <span style={{fontWeight: 700, color: '#6c5ce7'}}>{val}</span>
                </div>
              ))}
            </div>
          )}
          <div className="detail-actions">
            <button className="btn btn-warning" onClick={() => handleEdit(selected)}>Edit</button>
            <button className="btn btn-danger" onClick={() => handleDelete(selected.id)}>Delete</button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div className="page-header"><h1>Reports</h1><div className="header-actions"><button className="btn btn-primary" onClick={() => { setEditing(null); setForm(emptyForm); setShowForm(true); }}>+ New Report</button></div></div>

      <div className="detail-panel" style={{marginBottom: 24}}>
        <h2 style={{fontSize: 18}}>{'\u{1F916}'} AI Report Generator</h2>
        <div className="form-grid">
          <div className="form-group">
            <label>Report Type</label>
            <select value={reportType} onChange={e => setReportType(e.target.value)}>
              <option value="enrollment">Enrollment Summary</option>
              <option value="safety">Safety Overview</option>
              <option value="interim">Interim Analysis</option>
              <option value="performance">Site Performance</option>
              <option value="portfolio">Portfolio Overview</option>
            </select>
          </div>
          <div className="form-group">
            <label>Trial (Optional)</label>
            <select value={reportTrialId} onChange={e => setReportTrialId(e.target.value)}>
              <option value="">All Trials</option>
              {trials.map(t => <option key={t.id} value={t.id}>{t.trialId} - {t.title}</option>)}
            </select>
          </div>
        </div>
        <button className="btn btn-primary" onClick={handleAIReport} disabled={aiLoading}>Generate AI Report</button>
        {aiLoading && <div className="ai-loading" style={{marginTop: 16}}><div className="pulse"></div><p>AI is generating report...</p></div>}
        {aiResult && (
          <div style={{ marginTop: 16 }}>
            <AIResultDisplay result={aiResult} loading={false} error={null} />
          </div>
        )}
      </div>

      <div className="search-bar"><input placeholder="Search reports..." value={search} onChange={e => setSearch(e.target.value)} /></div>
      <div className="data-table-container">
        <table className="data-table">
          <thead><tr><th>Title</th><th>Type</th><th>Generated By</th><th>Format</th><th>Status</th><th>Date</th></tr></thead>
          <tbody>
            {filtered.map(r => (
              <tr key={r.id} onClick={() => setSelected(r)}>
                <td><strong>{r.title}</strong></td><td>{r.type}</td><td>{r.generatedBy}</td><td>{r.format}</td>
                <td><span className="badge badge-success">{r.status}</span></td>
                <td>{new Date(r.createdAt).toLocaleDateString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {showForm && (
        <div className="modal-overlay" onClick={() => setShowForm(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <h2>{editing ? 'Edit Report' : 'New Report'}</h2>
            <div className="form-grid">
              <div className="form-group full-width"><label>Title</label><input value={form.title} onChange={e => setForm({...form, title: e.target.value})} /></div>
              <div className="form-group"><label>Type</label><input value={form.type} onChange={e => setForm({...form, type: e.target.value})} /></div>
              <div className="form-group"><label>Format</label><select value={form.format} onChange={e => setForm({...form, format: e.target.value})}><option value="pdf">PDF</option><option value="excel">Excel</option><option value="csv">CSV</option></select></div>
              <div className="form-group"><label>Generated By</label><input value={form.generatedBy} onChange={e => setForm({...form, generatedBy: e.target.value})} /></div>
              <div className="form-group full-width"><label>Description</label><textarea value={form.description} onChange={e => setForm({...form, description: e.target.value})} /></div>
            </div>
            <div className="modal-actions">
              <button className="btn btn-secondary" onClick={() => setShowForm(false)}>Cancel</button>
              <button className="btn btn-primary" onClick={handleSave}>{editing ? 'Update' : 'Create'}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
