require('dotenv').config({ path: require('path').resolve(__dirname, '../../../.env') });
const bcrypt = require('bcryptjs');
const { sequelize, User, Patient, Trial, Match, Site, Enrollment, AdverseEvent, Protocol, Biomarker, DrugInteraction, Regulatory, Notification, Report, Eligibility, Outcome } = require('../models');

function requireDemoPassword() {
  const password = process.env.DEMO_PASSWORD || process.env.SEED_DEMO_PASSWORD || process.env.DEMO_SEED_PASSWORD || '';
  if (password.length < 12 || password.length > 1024) throw new Error('DEMO_PASSWORD must contain 12-1024 characters');
  return password;
}

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('Connected to database.');
    await sequelize.sync({ force: true });
    console.log('Tables created.');

    // Users
    const hashedPassword = await bcrypt.hash(requireDemoPassword(), 10);
    await User.bulkCreate([
      { email: 'admin@clinicaltrial.com', password: hashedPassword, name: 'Dr. Sarah Johnson', role: 'admin' },
      { email: 'researcher@clinicaltrial.com', password: hashedPassword, name: 'Dr. Michael Chen', role: 'researcher' },
      { email: 'coordinator@clinicaltrial.com', password: hashedPassword, name: 'Emily Davis', role: 'coordinator' },
    ]);

    // Patients (15+)
    const patients = await Patient.bulkCreate([
      { firstName: 'James', lastName: 'Wilson', dateOfBirth: '1965-03-15', gender: 'Male', email: 'jwilson@email.com', phone: '555-0101', diagnosis: 'Non-Small Cell Lung Cancer', stage: 'Stage IIIB', biomarkers: 'EGFR L858R+, PD-L1 80%, ALK-', medicalHistory: 'Hypertension, Type 2 Diabetes', currentMedications: 'Metformin 500mg, Lisinopril 10mg', status: 'active' },
      { firstName: 'Maria', lastName: 'Garcia', dateOfBirth: '1972-07-22', gender: 'Female', email: 'mgarcia@email.com', phone: '555-0102', diagnosis: 'Breast Cancer', stage: 'Stage II', biomarkers: 'HER2+, ER+, PR+, Ki-67 30%', medicalHistory: 'No significant history', currentMedications: 'Tamoxifen 20mg', status: 'active' },
      { firstName: 'Robert', lastName: 'Thompson', dateOfBirth: '1958-11-08', gender: 'Male', email: 'rthompson@email.com', phone: '555-0103', diagnosis: 'Colorectal Cancer', stage: 'Stage IV', biomarkers: 'KRAS G12D+, MSS, BRAF-', medicalHistory: 'Coronary artery disease, Previous colectomy', currentMedications: 'Aspirin 81mg, Atorvastatin 40mg', status: 'active' },
      { firstName: 'Linda', lastName: 'Anderson', dateOfBirth: '1970-01-20', gender: 'Female', email: 'landerson@email.com', phone: '555-0104', diagnosis: 'Ovarian Cancer', stage: 'Stage IIIC', biomarkers: 'BRCA1+, CA-125 elevated', medicalHistory: 'Previous oophorectomy', currentMedications: 'None', status: 'active' },
      { firstName: 'David', lastName: 'Martinez', dateOfBirth: '1980-05-12', gender: 'Male', email: 'dmartinez@email.com', phone: '555-0105', diagnosis: 'Melanoma', stage: 'Stage IIIA', biomarkers: 'BRAF V600E+, PD-L1 45%', medicalHistory: 'None significant', currentMedications: 'Dabrafenib, Trametinib', status: 'active' },
      { firstName: 'Susan', lastName: 'Brown', dateOfBirth: '1968-09-30', gender: 'Female', email: 'sbrown@email.com', phone: '555-0106', diagnosis: 'Pancreatic Cancer', stage: 'Stage IIB', biomarkers: 'KRAS G12V+, CA 19-9 elevated', medicalHistory: 'Type 2 Diabetes', currentMedications: 'Insulin Glargine', status: 'active' },
      { firstName: 'Michael', lastName: 'Davis', dateOfBirth: '1975-02-14', gender: 'Male', email: 'mdavis@email.com', phone: '555-0107', diagnosis: 'Prostate Cancer', stage: 'Stage III', biomarkers: 'PSA 15.2, AR-V7+, BRCA2+', medicalHistory: 'BPH', currentMedications: 'Enzalutamide', status: 'active' },
      { firstName: 'Jennifer', lastName: 'Taylor', dateOfBirth: '1962-12-05', gender: 'Female', email: 'jtaylor@email.com', phone: '555-0108', diagnosis: 'Acute Myeloid Leukemia', stage: 'Intermediate Risk', biomarkers: 'FLT3-ITD+, NPM1+', medicalHistory: 'Previous chemotherapy', currentMedications: 'Midostaurin', status: 'active' },
      { firstName: 'William', lastName: 'Lee', dateOfBirth: '1955-08-18', gender: 'Male', email: 'wlee@email.com', phone: '555-0109', diagnosis: 'Renal Cell Carcinoma', stage: 'Stage IV', biomarkers: 'PD-L1 60%, VHL mutated', medicalHistory: 'Hypertension, Nephrectomy', currentMedications: 'Sunitinib 50mg, Amlodipine 5mg', status: 'active' },
      { firstName: 'Patricia', lastName: 'Harris', dateOfBirth: '1978-04-25', gender: 'Female', email: 'pharris@email.com', phone: '555-0110', diagnosis: 'Triple-Negative Breast Cancer', stage: 'Stage IIIA', biomarkers: 'ER-, PR-, HER2-, PD-L1 70%, BRCA1+', medicalHistory: 'Family history of breast cancer', currentMedications: 'None', status: 'active' },
      { firstName: 'Thomas', lastName: 'Clark', dateOfBirth: '1960-06-10', gender: 'Male', email: 'tclark@email.com', phone: '555-0111', diagnosis: 'Hepatocellular Carcinoma', stage: 'Stage IIIA', biomarkers: 'AFP elevated, Hepatitis C+', medicalHistory: 'Cirrhosis, Hepatitis C', currentMedications: 'Sorafenib', status: 'active' },
      { firstName: 'Elizabeth', lastName: 'Walker', dateOfBirth: '1983-10-02', gender: 'Female', email: 'ewalker@email.com', phone: '555-0112', diagnosis: 'Glioblastoma', stage: 'Grade IV', biomarkers: 'MGMT methylated, IDH1 wild-type', medicalHistory: 'Seizures', currentMedications: 'Temozolomide, Levetiracetam', status: 'active' },
      { firstName: 'Richard', lastName: 'Hall', dateOfBirth: '1969-07-08', gender: 'Male', email: 'rhall@email.com', phone: '555-0113', diagnosis: 'Non-Hodgkin Lymphoma', stage: 'Stage IV', biomarkers: 'CD20+, Ki-67 85%', medicalHistory: 'None significant', currentMedications: 'R-CHOP regimen', status: 'active' },
      { firstName: 'Nancy', lastName: 'Allen', dateOfBirth: '1974-03-28', gender: 'Female', email: 'nallen@email.com', phone: '555-0114', diagnosis: 'Endometrial Cancer', stage: 'Stage II', biomarkers: 'MSI-H, PD-L1 55%, PTEN loss', medicalHistory: 'Obesity, Diabetes', currentMedications: 'Metformin 1000mg', status: 'active' },
      { firstName: 'Charles', lastName: 'Young', dateOfBirth: '1957-11-15', gender: 'Male', email: 'cyoung@email.com', phone: '555-0115', diagnosis: 'Bladder Cancer', stage: 'Stage III', biomarkers: 'PD-L1 40%, FGFR3 mutated', medicalHistory: 'Smoking history', currentMedications: 'Erdafitinib', status: 'active' },
      { firstName: 'Karen', lastName: 'King', dateOfBirth: '1966-08-20', gender: 'Female', email: 'kking@email.com', phone: '555-0116', diagnosis: 'Gastric Cancer', stage: 'Stage IIIB', biomarkers: 'HER2+, PD-L1 30%, MSS', medicalHistory: 'H. pylori infection history', currentMedications: 'Trastuzumab', status: 'active' },
    ]);

    // Clinical Trials (15+)
    const trials = await Trial.bulkCreate([
      { trialId: 'NCT-2024-001', title: 'Osimertinib + Savolitinib in EGFR-mutant NSCLC', description: 'Phase III study evaluating combination therapy in EGFR-mutant non-small cell lung cancer with MET amplification', phase: 'Phase III', status: 'recruiting', sponsor: 'AstraZeneca', therapeuticArea: 'Oncology', indication: 'Non-Small Cell Lung Cancer', startDate: '2024-01-15', endDate: '2026-12-31', targetEnrollment: 450, currentEnrollment: 178, eligibilityCriteria: 'EGFR mutation positive, Stage IIIB-IV, ECOG 0-1, No prior 3rd gen TKI', primaryEndpoint: 'Progression-Free Survival', secondaryEndpoints: 'Overall Survival, Objective Response Rate, Duration of Response' },
      { trialId: 'NCT-2024-002', title: 'Trastuzumab Deruxtecan in HER2+ Breast Cancer', description: 'Phase II study of T-DXd in HER2-positive metastatic breast cancer after prior trastuzumab', phase: 'Phase II', status: 'recruiting', sponsor: 'Daiichi Sankyo', therapeuticArea: 'Oncology', indication: 'Breast Cancer', startDate: '2024-03-01', endDate: '2026-06-30', targetEnrollment: 300, currentEnrollment: 142, eligibilityCriteria: 'HER2-positive, Prior trastuzumab therapy, Measurable disease, ECOG 0-1', primaryEndpoint: 'Objective Response Rate', secondaryEndpoints: 'PFS, OS, Duration of Response, Safety Profile' },
      { trialId: 'NCT-2024-003', title: 'Sotorasib + Panitumumab in KRAS G12C CRC', description: 'Phase III study of KRAS G12C inhibitor combination in colorectal cancer', phase: 'Phase III', status: 'recruiting', sponsor: 'Amgen', therapeuticArea: 'Oncology', indication: 'Colorectal Cancer', startDate: '2024-02-15', endDate: '2027-02-15', targetEnrollment: 500, currentEnrollment: 95, eligibilityCriteria: 'KRAS G12C mutation, Stage IV CRC, Prior oxaliplatin and irinotecan, ECOG 0-1', primaryEndpoint: 'Overall Survival', secondaryEndpoints: 'PFS, ORR, Disease Control Rate' },
      { trialId: 'NCT-2024-004', title: 'Olaparib + Bevacizumab in BRCA+ Ovarian Cancer', description: 'Phase III maintenance therapy study in BRCA-mutated ovarian cancer', phase: 'Phase III', status: 'recruiting', sponsor: 'AstraZeneca', therapeuticArea: 'Oncology', indication: 'Ovarian Cancer', startDate: '2024-04-01', endDate: '2027-04-01', targetEnrollment: 400, currentEnrollment: 210, eligibilityCriteria: 'BRCA1/2 mutation, High-grade serous ovarian cancer, Complete/partial response to platinum', primaryEndpoint: 'Progression-Free Survival', secondaryEndpoints: 'OS, Time to Second Progression, TFST' },
      { trialId: 'NCT-2024-005', title: 'Pembrolizumab + Lenvatinib in Advanced Melanoma', description: 'Phase II combination immunotherapy study in BRAF-mutant melanoma', phase: 'Phase II', status: 'recruiting', sponsor: 'Merck', therapeuticArea: 'Oncology', indication: 'Melanoma', startDate: '2024-05-01', endDate: '2026-11-30', targetEnrollment: 250, currentEnrollment: 88, eligibilityCriteria: 'BRAF V600 mutation, Stage III-IV melanoma, Prior BRAF/MEK inhibitor, ECOG 0-1', primaryEndpoint: 'Objective Response Rate', secondaryEndpoints: 'PFS, OS, Duration of Response' },
      { trialId: 'NCT-2024-006', title: 'Nab-Paclitaxel + Gemcitabine + Durvalumab in Pancreatic Cancer', description: 'Phase II/III immunotherapy combination in pancreatic ductal adenocarcinoma', phase: 'Phase II/III', status: 'recruiting', sponsor: 'AstraZeneca', therapeuticArea: 'Oncology', indication: 'Pancreatic Cancer', startDate: '2024-01-01', endDate: '2027-01-01', targetEnrollment: 350, currentEnrollment: 67, eligibilityCriteria: 'Pancreatic ductal adenocarcinoma, No prior systemic therapy, ECOG 0-1, Adequate organ function', primaryEndpoint: 'Overall Survival', secondaryEndpoints: 'PFS, ORR, Safety, Biomarker Analysis' },
      { trialId: 'NCT-2024-007', title: 'Enzalutamide + Talazoparib in mCRPC', description: 'Phase III PARP inhibitor combination in metastatic castration-resistant prostate cancer', phase: 'Phase III', status: 'recruiting', sponsor: 'Pfizer', therapeuticArea: 'Oncology', indication: 'Prostate Cancer', startDate: '2024-06-01', endDate: '2027-06-01', targetEnrollment: 600, currentEnrollment: 234, eligibilityCriteria: 'mCRPC, BRCA1/2 or ATM mutation, Prior abiraterone or enzalutamide, ECOG 0-2', primaryEndpoint: 'Radiographic PFS', secondaryEndpoints: 'OS, ORR, Time to PSA Progression' },
      { trialId: 'NCT-2024-008', title: 'Gilteritinib + Azacitidine in FLT3+ AML', description: 'Phase III study in FLT3-mutated acute myeloid leukemia', phase: 'Phase III', status: 'recruiting', sponsor: 'Astellas', therapeuticArea: 'Hematology', indication: 'Acute Myeloid Leukemia', startDate: '2024-03-15', endDate: '2027-03-15', targetEnrollment: 400, currentEnrollment: 156, eligibilityCriteria: 'FLT3-ITD or TKD mutation, Relapsed/refractory AML, ECOG 0-2, Adequate organ function', primaryEndpoint: 'Overall Survival', secondaryEndpoints: 'Complete Remission Rate, EFS, MRD Negativity' },
      { trialId: 'NCT-2024-009', title: 'Cabozantinib + Nivolumab + Ipilimumab in Advanced RCC', description: 'Phase III triplet combination in treatment-naive renal cell carcinoma', phase: 'Phase III', status: 'recruiting', sponsor: 'Exelixis', therapeuticArea: 'Oncology', indication: 'Renal Cell Carcinoma', startDate: '2024-02-01', endDate: '2027-08-01', targetEnrollment: 550, currentEnrollment: 189, eligibilityCriteria: 'Clear cell RCC, No prior systemic therapy, Intermediate/poor risk, ECOG 0-1', primaryEndpoint: 'Progression-Free Survival', secondaryEndpoints: 'OS, ORR, CR Rate, Safety' },
      { trialId: 'NCT-2024-010', title: 'Sacituzumab Govitecan + Pembrolizumab in TNBC', description: 'Phase III ADC + immunotherapy combination in triple-negative breast cancer', phase: 'Phase III', status: 'recruiting', sponsor: 'Gilead', therapeuticArea: 'Oncology', indication: 'Triple-Negative Breast Cancer', startDate: '2024-04-15', endDate: '2027-04-15', targetEnrollment: 400, currentEnrollment: 112, eligibilityCriteria: 'Triple-negative breast cancer, PD-L1 positive, 1-2 prior therapies, ECOG 0-1', primaryEndpoint: 'Progression-Free Survival', secondaryEndpoints: 'OS, ORR, Duration of Response, Safety' },
      { trialId: 'NCT-2024-011', title: 'Atezolizumab + Bevacizumab in HCC', description: 'Phase III immunotherapy combination in hepatocellular carcinoma', phase: 'Phase III', status: 'recruiting', sponsor: 'Roche', therapeuticArea: 'Oncology', indication: 'Hepatocellular Carcinoma', startDate: '2024-01-15', endDate: '2026-07-15', targetEnrollment: 480, currentEnrollment: 267, eligibilityCriteria: 'Unresectable HCC, Child-Pugh A, No prior systemic therapy, ECOG 0-1', primaryEndpoint: 'Overall Survival', secondaryEndpoints: 'PFS, ORR, Duration of Response' },
      { trialId: 'NCT-2024-012', title: 'Temozolomide + TTFields + Pembrolizumab in GBM', description: 'Phase II novel combination in newly diagnosed glioblastoma', phase: 'Phase II', status: 'recruiting', sponsor: 'Novocure', therapeuticArea: 'Neuro-Oncology', indication: 'Glioblastoma', startDate: '2024-05-15', endDate: '2026-11-15', targetEnrollment: 200, currentEnrollment: 45, eligibilityCriteria: 'Newly diagnosed GBM, MGMT methylated, KPS >= 70, Post-surgical resection', primaryEndpoint: 'Overall Survival', secondaryEndpoints: 'PFS, ORR, Quality of Life, Neurocognitive Function' },
      { trialId: 'NCT-2024-013', title: 'Glofitamab + Polatuzumab in R/R DLBCL', description: 'Phase III bispecific antibody combination in diffuse large B-cell lymphoma', phase: 'Phase III', status: 'recruiting', sponsor: 'Roche', therapeuticArea: 'Hematology', indication: 'Non-Hodgkin Lymphoma', startDate: '2024-03-01', endDate: '2027-03-01', targetEnrollment: 350, currentEnrollment: 98, eligibilityCriteria: 'CD20+ DLBCL, Relapsed after 2+ prior therapies, ECOG 0-2, Measurable disease', primaryEndpoint: 'Complete Response Rate', secondaryEndpoints: 'OS, PFS, Duration of Response, MRD' },
      { trialId: 'NCT-2024-014', title: 'Dostarlimab + Carboplatin in MSI-H Endometrial Cancer', description: 'Phase III immunotherapy in microsatellite instability-high endometrial cancer', phase: 'Phase III', status: 'recruiting', sponsor: 'GSK', therapeuticArea: 'Oncology', indication: 'Endometrial Cancer', startDate: '2024-06-01', endDate: '2027-06-01', targetEnrollment: 300, currentEnrollment: 76, eligibilityCriteria: 'MSI-H/dMMR endometrial cancer, Stage III-IV or recurrent, ECOG 0-1', primaryEndpoint: 'Progression-Free Survival', secondaryEndpoints: 'OS, ORR, Duration of Response, PROs' },
      { trialId: 'NCT-2024-015', title: 'Erdafitinib + Cetrelimab in FGFR+ Bladder Cancer', description: 'Phase III FGFR inhibitor + PD-1 combination in urothelial carcinoma', phase: 'Phase III', status: 'recruiting', sponsor: 'Janssen', therapeuticArea: 'Oncology', indication: 'Bladder Cancer', startDate: '2024-04-01', endDate: '2027-04-01', targetEnrollment: 450, currentEnrollment: 134, eligibilityCriteria: 'FGFR2/3 alteration, Locally advanced or metastatic UC, Prior platinum-based chemo, ECOG 0-1', primaryEndpoint: 'Overall Survival', secondaryEndpoints: 'PFS, ORR, Duration of Response, Safety' },
      { trialId: 'NCT-2024-016', title: 'Zolbetuximab + mFOLFOX6 in CLDN18.2+ Gastric Cancer', description: 'Phase III anti-CLDN18.2 combination in gastric/GEJ adenocarcinoma', phase: 'Phase III', status: 'recruiting', sponsor: 'Astellas', therapeuticArea: 'Oncology', indication: 'Gastric Cancer', startDate: '2024-02-15', endDate: '2027-02-15', targetEnrollment: 500, currentEnrollment: 201, eligibilityCriteria: 'CLDN18.2 positive, HER2 negative, First-line, Unresectable or metastatic, ECOG 0-1', primaryEndpoint: 'Overall Survival', secondaryEndpoints: 'PFS, ORR, Duration of Response, Safety, QoL' },
    ]);

    // Matches (15+)
    await Match.bulkCreate([
      { patientId: 1, trialId: 1, matchScore: 92.5, matchReason: 'EGFR L858R mutation matches trial criteria, Stage IIIB eligible', status: 'approved', aiAnalysis: 'Strong match based on EGFR mutation status and disease stage' },
      { patientId: 2, trialId: 2, matchScore: 88.0, matchReason: 'HER2+ status matches, prior trastuzumab eligible', status: 'pending', aiAnalysis: 'Good match for T-DXd trial based on HER2 status' },
      { patientId: 3, trialId: 3, matchScore: 65.0, matchReason: 'KRAS G12D (not G12C) - partial match only', status: 'review', aiAnalysis: 'KRAS mutation present but different variant than required' },
      { patientId: 4, trialId: 4, matchScore: 95.0, matchReason: 'BRCA1+ perfectly matches, high-grade serous ovarian cancer', status: 'approved', aiAnalysis: 'Excellent match for PARP inhibitor maintenance therapy' },
      { patientId: 5, trialId: 5, matchScore: 90.0, matchReason: 'BRAF V600E matches, Stage IIIA melanoma eligible', status: 'approved', aiAnalysis: 'Strong candidate for combination immunotherapy' },
      { patientId: 6, trialId: 6, matchScore: 82.0, matchReason: 'Pancreatic cancer with no prior systemic therapy', status: 'pending', aiAnalysis: 'Good candidate, diabetes management needed during trial' },
      { patientId: 7, trialId: 7, matchScore: 91.0, matchReason: 'BRCA2+ mCRPC matches perfectly for PARP combination', status: 'approved', aiAnalysis: 'Excellent match based on genetic profile' },
      { patientId: 8, trialId: 8, matchScore: 87.0, matchReason: 'FLT3-ITD+ matches trial criteria for AML', status: 'pending', aiAnalysis: 'Good match, NPM1 co-mutation may improve prognosis' },
      { patientId: 9, trialId: 9, matchScore: 78.0, matchReason: 'RCC with prior sunitinib - may need wash-out period', status: 'review', aiAnalysis: 'Potential match but prior TKI therapy needs evaluation' },
      { patientId: 10, trialId: 10, matchScore: 94.0, matchReason: 'TNBC with PD-L1 70% and BRCA1+ - ideal candidate', status: 'approved', aiAnalysis: 'Excellent candidate for ADC + immunotherapy combination' },
      { patientId: 11, trialId: 11, matchScore: 75.0, matchReason: 'HCC with cirrhosis - need to verify Child-Pugh status', status: 'review', aiAnalysis: 'Match dependent on liver function assessment' },
      { patientId: 12, trialId: 12, matchScore: 89.0, matchReason: 'GBM with MGMT methylation matches trial criteria', status: 'approved', aiAnalysis: 'Strong match for novel combination therapy' },
      { patientId: 13, trialId: 13, matchScore: 85.0, matchReason: 'CD20+ NHL after prior R-CHOP eligible for bispecific', status: 'pending', aiAnalysis: 'Good candidate if R-CHOP considered prior therapy' },
      { patientId: 14, trialId: 14, matchScore: 93.0, matchReason: 'MSI-H endometrial cancer - ideal for immunotherapy trial', status: 'approved', aiAnalysis: 'Excellent match based on MSI-H and PD-L1 status' },
      { patientId: 15, trialId: 15, matchScore: 88.0, matchReason: 'FGFR3 mutation in bladder cancer matches trial requirements', status: 'pending', aiAnalysis: 'Good match for FGFR inhibitor combination' },
      { patientId: 16, trialId: 16, matchScore: 70.0, matchReason: 'Gastric cancer HER2+ may exclude from CLDN18.2 trial', status: 'review', aiAnalysis: 'HER2 status needs verification for eligibility' },
    ]);

    // Sites (15+)
    await Site.bulkCreate([
      { name: 'Massachusetts General Hospital', address: '55 Fruit St', city: 'Boston', state: 'MA', country: 'USA', zipCode: '02114', principalInvestigator: 'Dr. Alice Nguyen', contactEmail: 'trials@mgh.edu', contactPhone: '617-555-0001', capacity: 200, activeTrials: 12, status: 'active' },
      { name: 'MD Anderson Cancer Center', address: '1515 Holcombe Blvd', city: 'Houston', state: 'TX', country: 'USA', zipCode: '77030', principalInvestigator: 'Dr. Robert Kim', contactEmail: 'trials@mdanderson.org', contactPhone: '713-555-0002', capacity: 350, activeTrials: 25, status: 'active' },
      { name: 'Memorial Sloan Kettering', address: '1275 York Ave', city: 'New York', state: 'NY', country: 'USA', zipCode: '10065', principalInvestigator: 'Dr. Sarah Williams', contactEmail: 'trials@mskcc.org', contactPhone: '212-555-0003', capacity: 300, activeTrials: 20, status: 'active' },
      { name: 'Mayo Clinic', address: '200 First St SW', city: 'Rochester', state: 'MN', country: 'USA', zipCode: '55905', principalInvestigator: 'Dr. James Thompson', contactEmail: 'trials@mayo.edu', contactPhone: '507-555-0004', capacity: 250, activeTrials: 18, status: 'active' },
      { name: 'Johns Hopkins Hospital', address: '1800 Orleans St', city: 'Baltimore', state: 'MD', country: 'USA', zipCode: '21287', principalInvestigator: 'Dr. Maria Gonzalez', contactEmail: 'trials@jhmi.edu', contactPhone: '410-555-0005', capacity: 180, activeTrials: 14, status: 'active' },
      { name: 'Dana-Farber Cancer Institute', address: '450 Brookline Ave', city: 'Boston', state: 'MA', country: 'USA', zipCode: '02215', principalInvestigator: 'Dr. David Lee', contactEmail: 'trials@dfci.org', contactPhone: '617-555-0006', capacity: 220, activeTrials: 16, status: 'active' },
      { name: 'Cleveland Clinic', address: '9500 Euclid Ave', city: 'Cleveland', state: 'OH', country: 'USA', zipCode: '44195', principalInvestigator: 'Dr. Emily Chen', contactEmail: 'trials@ccf.org', contactPhone: '216-555-0007', capacity: 160, activeTrials: 10, status: 'active' },
      { name: 'Stanford Cancer Center', address: '875 Blake Wilbur Dr', city: 'Stanford', state: 'CA', country: 'USA', zipCode: '94305', principalInvestigator: 'Dr. Kevin Park', contactEmail: 'trials@stanford.edu', contactPhone: '650-555-0008', capacity: 190, activeTrials: 15, status: 'active' },
      { name: 'UCLA Medical Center', address: '757 Westwood Plaza', city: 'Los Angeles', state: 'CA', country: 'USA', zipCode: '90095', principalInvestigator: 'Dr. Lisa Anderson', contactEmail: 'trials@ucla.edu', contactPhone: '310-555-0009', capacity: 210, activeTrials: 13, status: 'active' },
      { name: 'University of Chicago Medicine', address: '5841 S Maryland Ave', city: 'Chicago', state: 'IL', country: 'USA', zipCode: '60637', principalInvestigator: 'Dr. Richard Brown', contactEmail: 'trials@uchicago.edu', contactPhone: '773-555-0010', capacity: 170, activeTrials: 11, status: 'active' },
      { name: 'Duke Cancer Institute', address: '20 Duke Medicine Cir', city: 'Durham', state: 'NC', country: 'USA', zipCode: '27710', principalInvestigator: 'Dr. Patricia Davis', contactEmail: 'trials@duke.edu', contactPhone: '919-555-0011', capacity: 200, activeTrials: 14, status: 'active' },
      { name: 'UCSF Helen Diller Cancer Center', address: '1825 4th St', city: 'San Francisco', state: 'CA', country: 'USA', zipCode: '94158', principalInvestigator: 'Dr. Thomas Wilson', contactEmail: 'trials@ucsf.edu', contactPhone: '415-555-0012', capacity: 180, activeTrials: 12, status: 'active' },
      { name: 'Penn Medicine', address: '3400 Civic Center Blvd', city: 'Philadelphia', state: 'PA', country: 'USA', zipCode: '19104', principalInvestigator: 'Dr. Jennifer Martinez', contactEmail: 'trials@pennmedicine.org', contactPhone: '215-555-0013', capacity: 230, activeTrials: 17, status: 'active' },
      { name: 'Moffitt Cancer Center', address: '12902 USF Magnolia Dr', city: 'Tampa', state: 'FL', country: 'USA', zipCode: '33612', principalInvestigator: 'Dr. William Taylor', contactEmail: 'trials@moffitt.org', contactPhone: '813-555-0014', capacity: 150, activeTrials: 9, status: 'active' },
      { name: 'Fred Hutchinson Cancer Center', address: '1100 Fairview Ave N', city: 'Seattle', state: 'WA', country: 'USA', zipCode: '98109', principalInvestigator: 'Dr. Nancy Harris', contactEmail: 'trials@fredhutch.org', contactPhone: '206-555-0015', capacity: 190, activeTrials: 13, status: 'active' },
    ]);

    // Enrollments (15+)
    await Enrollment.bulkCreate([
      { patientId: 1, trialId: 1, siteId: 1, enrollmentDate: '2024-06-15', status: 'enrolled', consentDate: '2024-06-10', screeningResult: 'pass', notes: 'Patient meets all eligibility criteria' },
      { patientId: 2, trialId: 2, siteId: 2, enrollmentDate: '2024-07-01', status: 'enrolled', consentDate: '2024-06-25', screeningResult: 'pass', notes: 'HER2 status confirmed by central lab' },
      { patientId: 4, trialId: 4, siteId: 3, enrollmentDate: '2024-08-10', status: 'enrolled', consentDate: '2024-08-05', screeningResult: 'pass', notes: 'BRCA1 confirmed by genetic testing' },
      { patientId: 5, trialId: 5, siteId: 4, enrollmentDate: '2024-07-20', status: 'enrolled', consentDate: '2024-07-15', screeningResult: 'pass', notes: 'BRAF V600E confirmed' },
      { patientId: 7, trialId: 7, siteId: 5, enrollmentDate: '2024-09-01', status: 'screening', consentDate: '2024-08-28', screeningResult: 'pending', notes: 'Awaiting genetic test results' },
      { patientId: 8, trialId: 8, siteId: 6, enrollmentDate: '2024-08-15', status: 'enrolled', consentDate: '2024-08-10', screeningResult: 'pass', notes: 'FLT3-ITD confirmed by NGS' },
      { patientId: 10, trialId: 10, siteId: 7, enrollmentDate: '2024-09-10', status: 'screening', consentDate: '2024-09-05', screeningResult: 'pending', notes: 'PD-L1 retesting in progress' },
      { patientId: 12, trialId: 12, siteId: 8, enrollmentDate: '2024-10-01', status: 'enrolled', consentDate: '2024-09-25', screeningResult: 'pass', notes: 'Post-surgical resection confirmed' },
      { patientId: 14, trialId: 14, siteId: 9, enrollmentDate: '2024-10-15', status: 'enrolled', consentDate: '2024-10-10', screeningResult: 'pass', notes: 'MSI-H status confirmed by IHC' },
      { patientId: 15, trialId: 15, siteId: 10, enrollmentDate: '2024-11-01', status: 'screening', consentDate: '2024-10-28', screeningResult: 'pending', notes: 'FGFR3 alteration verification ongoing' },
      { patientId: 3, trialId: 3, siteId: 11, enrollmentDate: '2024-07-15', status: 'screen_fail', consentDate: '2024-07-10', screeningResult: 'fail', notes: 'KRAS G12D not G12C - ineligible' },
      { patientId: 6, trialId: 6, siteId: 12, enrollmentDate: '2024-08-20', status: 'enrolled', consentDate: '2024-08-15', screeningResult: 'pass', notes: 'Diabetes well-controlled, eligible' },
      { patientId: 9, trialId: 9, siteId: 13, enrollmentDate: '2024-09-20', status: 'withdrawn', consentDate: '2024-09-15', screeningResult: 'pass', notes: 'Patient withdrew consent due to travel distance' },
      { patientId: 11, trialId: 11, siteId: 14, enrollmentDate: '2024-10-05', status: 'enrolled', consentDate: '2024-10-01', screeningResult: 'pass', notes: 'Child-Pugh A confirmed' },
      { patientId: 13, trialId: 13, siteId: 15, enrollmentDate: '2024-10-20', status: 'screening', consentDate: '2024-10-15', screeningResult: 'pending', notes: 'CD20 status being verified' },
      { patientId: 16, trialId: 16, siteId: 1, enrollmentDate: '2024-11-10', status: 'screening', consentDate: '2024-11-05', screeningResult: 'pending', notes: 'CLDN18.2 and HER2 testing in progress' },
    ]);

    // Adverse Events (15+)
    await AdverseEvent.bulkCreate([
      { patientId: 1, trialId: 1, eventType: 'Rash', severity: 'Grade 2', description: 'Acneiform rash on face and trunk', onsetDate: '2024-07-20', resolutionDate: '2024-08-05', outcome: 'Resolved', relatedness: 'Probable', actionTaken: 'Topical corticosteroids', status: 'closed' },
      { patientId: 1, trialId: 1, eventType: 'Diarrhea', severity: 'Grade 1', description: 'Mild diarrhea, 3-4 episodes per day', onsetDate: '2024-07-25', resolutionDate: '2024-08-01', outcome: 'Resolved', relatedness: 'Possible', actionTaken: 'Loperamide', status: 'closed' },
      { patientId: 2, trialId: 2, eventType: 'Nausea', severity: 'Grade 2', description: 'Moderate nausea requiring antiemetics', onsetDate: '2024-08-10', resolutionDate: '2024-08-20', outcome: 'Resolved', relatedness: 'Probable', actionTaken: 'Ondansetron', status: 'closed' },
      { patientId: 4, trialId: 4, eventType: 'Fatigue', severity: 'Grade 2', description: 'Persistent fatigue affecting daily activities', onsetDate: '2024-09-01', outcome: 'Ongoing', relatedness: 'Probable', actionTaken: 'Dose reduction', status: 'open' },
      { patientId: 5, trialId: 5, eventType: 'Hypothyroidism', severity: 'Grade 2', description: 'TSH elevated, new onset hypothyroidism', onsetDate: '2024-09-15', outcome: 'Ongoing', relatedness: 'Probable', actionTaken: 'Levothyroxine started', status: 'open' },
      { patientId: 6, trialId: 6, eventType: 'Neutropenia', severity: 'Grade 3', description: 'ANC 800/uL, febrile neutropenia episode', onsetDate: '2024-09-20', resolutionDate: '2024-09-30', outcome: 'Resolved', relatedness: 'Definite', actionTaken: 'G-CSF, dose delay', status: 'closed' },
      { patientId: 8, trialId: 8, eventType: 'Hepatotoxicity', severity: 'Grade 2', description: 'ALT/AST elevated 3x ULN', onsetDate: '2024-09-25', resolutionDate: '2024-10-10', outcome: 'Resolved', relatedness: 'Probable', actionTaken: 'Treatment hold, monitoring', status: 'closed' },
      { patientId: 12, trialId: 12, eventType: 'Headache', severity: 'Grade 1', description: 'Mild headaches during TTFields treatment', onsetDate: '2024-10-10', outcome: 'Ongoing', relatedness: 'Probable', actionTaken: 'Acetaminophen PRN', status: 'open' },
      { patientId: 14, trialId: 14, eventType: 'Immune-related colitis', severity: 'Grade 2', description: 'Diarrhea with abdominal cramping', onsetDate: '2024-11-01', outcome: 'Ongoing', relatedness: 'Probable', actionTaken: 'Oral corticosteroids', status: 'open' },
      { patientId: 2, trialId: 2, eventType: 'Interstitial Lung Disease', severity: 'Grade 1', description: 'Asymptomatic ground-glass opacities on CT', onsetDate: '2024-10-15', outcome: 'Monitoring', relatedness: 'Possible', actionTaken: 'Close monitoring, follow-up CT', status: 'open' },
      { patientId: 5, trialId: 5, eventType: 'Hypertension', severity: 'Grade 2', description: 'BP consistently 150-160/90-95', onsetDate: '2024-10-01', outcome: 'Ongoing', relatedness: 'Probable', actionTaken: 'Amlodipine started', status: 'open' },
      { patientId: 11, trialId: 11, eventType: 'Proteinuria', severity: 'Grade 2', description: 'Protein/creatinine ratio elevated', onsetDate: '2024-11-05', outcome: 'Ongoing', relatedness: 'Probable', actionTaken: 'Monitoring, dose adjustment', status: 'open' },
      { patientId: 7, trialId: 7, eventType: 'Anemia', severity: 'Grade 2', description: 'Hemoglobin 9.0 g/dL', onsetDate: '2024-10-10', outcome: 'Ongoing', relatedness: 'Probable', actionTaken: 'Transfusion, EPO considered', status: 'open' },
      { patientId: 1, trialId: 1, eventType: 'Pneumonitis', severity: 'Grade 1', description: 'Mild cough, minimal ground-glass changes', onsetDate: '2024-11-10', outcome: 'Monitoring', relatedness: 'Possible', actionTaken: 'Observation', status: 'open' },
      { patientId: 6, trialId: 6, eventType: 'Thrombocytopenia', severity: 'Grade 2', description: 'Platelet count 65,000/uL', onsetDate: '2024-10-20', resolutionDate: '2024-11-01', outcome: 'Resolved', relatedness: 'Probable', actionTaken: 'Dose delay', status: 'closed' },
    ]);

    // Protocols (15+)
    await Protocol.bulkCreate([
      { trialId: 1, protocolNumber: 'PROTO-2024-001', title: 'Osimertinib + Savolitinib Combination Protocol', version: '3.0', status: 'approved', approvalDate: '2024-01-10', amendmentNumber: 2, summary: 'Randomized, double-blind Phase III study', objectives: 'Evaluate PFS superiority of combination vs monotherapy', studyDesign: 'Randomized 1:1, double-blind, placebo-controlled', dosageRegimen: 'Osimertinib 80mg QD + Savolitinib 300mg BID' },
      { trialId: 2, protocolNumber: 'PROTO-2024-002', title: 'T-DXd in HER2+ mBC Protocol', version: '2.1', status: 'approved', approvalDate: '2024-02-20', amendmentNumber: 1, summary: 'Open-label Phase II study of T-DXd', objectives: 'Evaluate ORR in HER2+ mBC after prior anti-HER2 therapy', studyDesign: 'Single-arm, open-label, multicenter', dosageRegimen: 'T-DXd 5.4 mg/kg IV Q3W' },
      { trialId: 3, protocolNumber: 'PROTO-2024-003', title: 'Sotorasib + Panitumumab in CRC Protocol', version: '2.0', status: 'approved', approvalDate: '2024-02-01', amendmentNumber: 1, summary: 'Phase III study of KRAS G12C inhibitor + anti-EGFR', objectives: 'Evaluate OS benefit of combination therapy', studyDesign: 'Randomized 2:1, open-label', dosageRegimen: 'Sotorasib 960mg QD + Panitumumab 6mg/kg Q2W' },
      { trialId: 4, protocolNumber: 'PROTO-2024-004', title: 'Olaparib + Bevacizumab Maintenance Protocol', version: '4.0', status: 'approved', approvalDate: '2024-03-15', amendmentNumber: 3, summary: 'Phase III maintenance study in BRCA+ OC', objectives: 'Evaluate PFS with dual maintenance therapy', studyDesign: 'Randomized 1:1:1, double-blind', dosageRegimen: 'Olaparib 300mg BID + Bevacizumab 15mg/kg Q3W' },
      { trialId: 5, protocolNumber: 'PROTO-2024-005', title: 'Pembrolizumab + Lenvatinib Melanoma Protocol', version: '1.2', status: 'approved', approvalDate: '2024-04-20', amendmentNumber: 0, summary: 'Phase II combination immunotherapy study', objectives: 'Evaluate ORR in BRAF-mutant melanoma', studyDesign: 'Single-arm, open-label, Phase II', dosageRegimen: 'Pembrolizumab 200mg Q3W + Lenvatinib 20mg QD' },
      { trialId: 6, protocolNumber: 'PROTO-2024-006', title: 'Nab-Pac + Gem + Durvalumab in PDAC Protocol', version: '2.0', status: 'approved', approvalDate: '2023-12-10', amendmentNumber: 1, summary: 'Phase II/III immunotherapy combination in PDAC', objectives: 'Evaluate OS with immunotherapy addition to standard chemo', studyDesign: 'Randomized 1:1, double-blind, Phase II/III', dosageRegimen: 'Nab-paclitaxel 125mg/m2 + Gemcitabine 1000mg/m2 D1,8,15 + Durvalumab 1500mg Q4W' },
      { trialId: 7, protocolNumber: 'PROTO-2024-007', title: 'Enzalutamide + Talazoparib mCRPC Protocol', version: '3.1', status: 'approved', approvalDate: '2024-05-15', amendmentNumber: 2, summary: 'Phase III PARP combination in mCRPC', objectives: 'Evaluate rPFS with PARP + AR inhibitor combination', studyDesign: 'Randomized 1:1, double-blind, placebo-controlled', dosageRegimen: 'Enzalutamide 160mg QD + Talazoparib 0.5mg QD' },
      { trialId: 8, protocolNumber: 'PROTO-2024-008', title: 'Gilteritinib + Azacitidine AML Protocol', version: '2.0', status: 'approved', approvalDate: '2024-03-01', amendmentNumber: 1, summary: 'Phase III study in FLT3+ AML', objectives: 'Evaluate OS with FLT3 inhibitor combination', studyDesign: 'Randomized 2:1, open-label', dosageRegimen: 'Gilteritinib 120mg QD + Azacitidine 75mg/m2 D1-7 Q28D' },
      { trialId: 9, protocolNumber: 'PROTO-2024-009', title: 'Cabo + Nivo + Ipi in RCC Protocol', version: '1.5', status: 'approved', approvalDate: '2024-01-20', amendmentNumber: 0, summary: 'Phase III triplet combination in RCC', objectives: 'Evaluate PFS with triplet therapy in first-line', studyDesign: 'Randomized 1:1, open-label', dosageRegimen: 'Cabozantinib 40mg QD + Nivolumab 240mg Q2W + Ipilimumab 1mg/kg Q6W' },
      { trialId: 10, protocolNumber: 'PROTO-2024-010', title: 'SG + Pembrolizumab TNBC Protocol', version: '2.0', status: 'approved', approvalDate: '2024-04-01', amendmentNumber: 1, summary: 'Phase III ADC + IO combination in TNBC', objectives: 'Evaluate PFS and OS with ADC + IO combination', studyDesign: 'Randomized 1:1, open-label', dosageRegimen: 'SG 10mg/kg D1,8 Q21D + Pembrolizumab 200mg Q3W' },
      { trialId: 11, protocolNumber: 'PROTO-2024-011', title: 'Atezo + Bev in HCC Protocol', version: '3.0', status: 'approved', approvalDate: '2024-01-05', amendmentNumber: 2, summary: 'Phase III IO + anti-VEGF in HCC', objectives: 'Evaluate OS in first-line HCC', studyDesign: 'Randomized 1:1, open-label', dosageRegimen: 'Atezolizumab 1200mg + Bevacizumab 15mg/kg Q3W' },
      { trialId: 12, protocolNumber: 'PROTO-2024-012', title: 'TMZ + TTFields + Pembro in GBM Protocol', version: '1.0', status: 'approved', approvalDate: '2024-05-01', amendmentNumber: 0, summary: 'Phase II novel combination in GBM', objectives: 'Evaluate OS with TTFields + immunotherapy', studyDesign: 'Single-arm, open-label, Phase II', dosageRegimen: 'TMZ 150-200mg/m2 D1-5 Q28D + TTFields 200kHz + Pembrolizumab 200mg Q3W' },
      { trialId: 13, protocolNumber: 'PROTO-2024-013', title: 'Glofitamab + Pola in R/R DLBCL Protocol', version: '2.1', status: 'approved', approvalDate: '2024-02-25', amendmentNumber: 1, summary: 'Phase III bispecific + ADC in DLBCL', objectives: 'Evaluate CR rate with bispecific + ADC combination', studyDesign: 'Randomized 1:1, open-label', dosageRegimen: 'Glofitamab step-up dosing to 30mg + Polatuzumab 1.8mg/kg Q3W' },
      { trialId: 14, protocolNumber: 'PROTO-2024-014', title: 'Dostarlimab + Carboplatin in EC Protocol', version: '1.1', status: 'approved', approvalDate: '2024-05-20', amendmentNumber: 0, summary: 'Phase III IO + chemo in MSI-H EC', objectives: 'Evaluate PFS with IO addition', studyDesign: 'Randomized 1:1, double-blind', dosageRegimen: 'Dostarlimab 500mg Q3W x 6 then 1000mg Q6W + Carboplatin AUC5 Q3W x 6' },
      { trialId: 15, protocolNumber: 'PROTO-2024-015', title: 'Erdafitinib + Cetrelimab in UC Protocol', version: '2.0', status: 'approved', approvalDate: '2024-03-25', amendmentNumber: 1, summary: 'Phase III FGFR + PD-1 in urothelial cancer', objectives: 'Evaluate OS with FGFR + IO combination', studyDesign: 'Randomized 1:1, open-label', dosageRegimen: 'Erdafitinib 8mg QD + Cetrelimab 240mg Q3W' },
    ]);

    // Biomarkers (15+)
    await Biomarker.bulkCreate([
      { patientId: 1, name: 'EGFR L858R', value: 'Positive', unit: '', testDate: '2024-06-01', normalRange: 'Negative', status: 'abnormal', category: 'Genomic', significance: 'Predictive for EGFR TKI response' },
      { patientId: 1, name: 'PD-L1 TPS', value: '80', unit: '%', testDate: '2024-06-01', normalRange: '<1%', status: 'abnormal', category: 'Immunologic', significance: 'High expression, eligible for immunotherapy' },
      { patientId: 2, name: 'HER2 IHC', value: '3+', unit: '', testDate: '2024-06-15', normalRange: '0-1+', status: 'abnormal', category: 'Protein', significance: 'Strongly positive, eligible for anti-HER2 therapy' },
      { patientId: 2, name: 'Ki-67', value: '30', unit: '%', testDate: '2024-06-15', normalRange: '<14%', status: 'abnormal', category: 'Proliferation', significance: 'High proliferation index, aggressive biology' },
      { patientId: 3, name: 'KRAS G12D', value: 'Positive', unit: '', testDate: '2024-07-01', normalRange: 'Negative', status: 'abnormal', category: 'Genomic', significance: 'Oncogenic driver, limited targeted options' },
      { patientId: 4, name: 'BRCA1', value: 'Pathogenic variant', unit: '', testDate: '2024-07-20', normalRange: 'Wild-type', status: 'abnormal', category: 'Genomic', significance: 'Eligible for PARP inhibitor therapy' },
      { patientId: 4, name: 'CA-125', value: '450', unit: 'U/mL', testDate: '2024-08-01', normalRange: '<35 U/mL', status: 'abnormal', category: 'Tumor Marker', significance: 'Elevated, indicates active disease' },
      { patientId: 5, name: 'BRAF V600E', value: 'Positive', unit: '', testDate: '2024-07-01', normalRange: 'Negative', status: 'abnormal', category: 'Genomic', significance: 'Targetable with BRAF/MEK inhibitors' },
      { patientId: 7, name: 'PSA', value: '15.2', unit: 'ng/mL', testDate: '2024-08-15', normalRange: '<4.0 ng/mL', status: 'abnormal', category: 'Tumor Marker', significance: 'Elevated, active prostate cancer' },
      { patientId: 7, name: 'BRCA2', value: 'Pathogenic variant', unit: '', testDate: '2024-08-10', normalRange: 'Wild-type', status: 'abnormal', category: 'Genomic', significance: 'Eligible for PARP inhibitor therapy' },
      { patientId: 8, name: 'FLT3-ITD', value: 'Positive', unit: '', testDate: '2024-08-01', normalRange: 'Negative', status: 'abnormal', category: 'Genomic', significance: 'Targetable with FLT3 inhibitors, poor prognosis' },
      { patientId: 10, name: 'PD-L1 CPS', value: '70', unit: '', testDate: '2024-09-01', normalRange: '<1', status: 'abnormal', category: 'Immunologic', significance: 'High expression, strong immunotherapy candidate' },
      { patientId: 12, name: 'MGMT Methylation', value: 'Methylated', unit: '', testDate: '2024-09-20', normalRange: 'Unmethylated', status: 'favorable', category: 'Epigenomic', significance: 'Better prognosis, TMZ responsive' },
      { patientId: 14, name: 'MSI Status', value: 'MSI-High', unit: '', testDate: '2024-10-01', normalRange: 'MSS', status: 'abnormal', category: 'Genomic', significance: 'Eligible for immunotherapy, better prognosis' },
      { patientId: 15, name: 'FGFR3', value: 'S249C Mutation', unit: '', testDate: '2024-10-15', normalRange: 'Wild-type', status: 'abnormal', category: 'Genomic', significance: 'Targetable with FGFR inhibitors' },
      { patientId: 9, name: 'VHL', value: 'Mutated', unit: '', testDate: '2024-09-01', normalRange: 'Wild-type', status: 'abnormal', category: 'Genomic', significance: 'Common in clear cell RCC, VEGF pathway activated' },
    ]);

    // Drug Interactions (15+)
    await DrugInteraction.bulkCreate([
      { drugA: 'Osimertinib', drugB: 'Metformin', interactionType: 'Pharmacokinetic', severity: 'Low', description: 'Minimal interaction, monitor blood glucose', recommendation: 'Continue both, monitor glucose levels', evidenceLevel: 'Moderate', mechanism: 'Osimertinib may slightly affect renal OCT transporters' },
      { drugA: 'Tamoxifen', drugB: 'Trastuzumab Deruxtecan', interactionType: 'Pharmacodynamic', severity: 'Moderate', description: 'Potential antagonistic effect on HER2 signaling', recommendation: 'Consider discontinuing tamoxifen during T-DXd therapy', evidenceLevel: 'Low', mechanism: 'Opposing effects on estrogen receptor and HER2 pathways' },
      { drugA: 'Aspirin', drugB: 'Sotorasib', interactionType: 'Pharmacokinetic', severity: 'Low', description: 'No significant interaction expected', recommendation: 'Continue both medications', evidenceLevel: 'High', mechanism: 'Different metabolic pathways' },
      { drugA: 'Olaparib', drugB: 'Bevacizumab', interactionType: 'Pharmacodynamic', severity: 'Moderate', description: 'Combination may increase myelosuppression risk', recommendation: 'Monitor CBC regularly, dose adjust as needed', evidenceLevel: 'High', mechanism: 'Additive myelosuppressive effects' },
      { drugA: 'Dabrafenib', drugB: 'Pembrolizumab', interactionType: 'Pharmacodynamic', severity: 'Moderate', description: 'Sequential use may enhance immune response', recommendation: 'Monitor for immune-related adverse events', evidenceLevel: 'Moderate', mechanism: 'BRAF inhibition may increase tumor antigen presentation' },
      { drugA: 'Insulin Glargine', drugB: 'Gemcitabine', interactionType: 'Pharmacodynamic', severity: 'High', description: 'Gemcitabine may cause hyperglycemia', recommendation: 'Increase glucose monitoring, adjust insulin dose', evidenceLevel: 'High', mechanism: 'Gemcitabine affects pancreatic beta cells' },
      { drugA: 'Enzalutamide', drugB: 'Talazoparib', interactionType: 'Pharmacokinetic', severity: 'Moderate', description: 'Enzalutamide is a CYP3A4 inducer, may reduce talazoparib levels', recommendation: 'Use adjusted talazoparib dose (0.5mg instead of 1mg)', evidenceLevel: 'High', mechanism: 'CYP3A4/P-gp induction by enzalutamide' },
      { drugA: 'Midostaurin', drugB: 'Azacitidine', interactionType: 'Pharmacodynamic', severity: 'Moderate', description: 'Additive myelosuppression risk', recommendation: 'Monitor CBC, consider dose modifications', evidenceLevel: 'Moderate', mechanism: 'Both agents cause myelosuppression' },
      { drugA: 'Sunitinib', drugB: 'Amlodipine', interactionType: 'Pharmacokinetic', severity: 'Low', description: 'Both metabolized by CYP3A4, minimal clinical impact', recommendation: 'Continue both, monitor blood pressure', evidenceLevel: 'Moderate', mechanism: 'Competitive CYP3A4 metabolism' },
      { drugA: 'Sorafenib', drugB: 'Atezolizumab', interactionType: 'Pharmacodynamic', severity: 'Moderate', description: 'Sorafenib may modulate immune microenvironment', recommendation: 'Monitor liver function and immune-related AEs', evidenceLevel: 'Moderate', mechanism: 'VEGF inhibition may affect T-cell infiltration' },
      { drugA: 'Temozolomide', drugB: 'Levetiracetam', interactionType: 'Pharmacokinetic', severity: 'Low', description: 'No significant interaction', recommendation: 'Continue both medications', evidenceLevel: 'High', mechanism: 'Different metabolic pathways' },
      { drugA: 'Pembrolizumab', drugB: 'Levothyroxine', interactionType: 'Pharmacodynamic', severity: 'Low', description: 'Pembrolizumab may cause thyroid dysfunction', recommendation: 'Monitor thyroid function Q6W', evidenceLevel: 'High', mechanism: 'Immune-mediated thyroiditis' },
      { drugA: 'Erdafitinib', drugB: 'Cetrelimab', interactionType: 'Pharmacodynamic', severity: 'Moderate', description: 'Combination may increase skin toxicity', recommendation: 'Monitor for skin adverse events', evidenceLevel: 'Low', mechanism: 'Additive dermatologic effects from FGFR + PD-1' },
      { drugA: 'Metformin', drugB: 'Dostarlimab', interactionType: 'Pharmacodynamic', severity: 'Low', description: 'Metformin may enhance immunotherapy response', recommendation: 'Continue both, potential synergistic benefit', evidenceLevel: 'Low', mechanism: 'Metformin may modulate tumor metabolism and immune response' },
      { drugA: 'Trastuzumab', drugB: 'Zolbetuximab', interactionType: 'Pharmacodynamic', severity: 'High', description: 'Dual antibody therapy may increase cardiotoxicity', recommendation: 'Concurrent use contraindicated in trial', evidenceLevel: 'Moderate', mechanism: 'Additive cardiac stress from dual targeted antibodies' },
    ]);

    // Regulatory Documents (15+)
    await Regulatory.bulkCreate([
      { trialId: 1, documentType: 'IND Application', title: 'IND 150234 - Osimertinib + Savolitinib', status: 'approved', submissionDate: '2023-09-15', approvalDate: '2023-11-20', expiryDate: '2026-11-20', authority: 'FDA', referenceNumber: 'IND-150234', notes: 'Approved with no clinical hold' },
      { trialId: 1, documentType: 'IRB Approval', title: 'IRB Approval - Protocol PROTO-2024-001', status: 'approved', submissionDate: '2023-10-01', approvalDate: '2023-12-01', expiryDate: '2024-12-01', authority: 'Western IRB', referenceNumber: 'IRB-2023-4521', notes: 'Annual renewal required' },
      { trialId: 2, documentType: 'IND Application', title: 'IND 150456 - Trastuzumab Deruxtecan', status: 'approved', submissionDate: '2023-11-01', approvalDate: '2024-01-15', expiryDate: '2027-01-15', authority: 'FDA', referenceNumber: 'IND-150456', notes: 'Cross-reference to DS-8201 IND' },
      { trialId: 3, documentType: 'EMA Authorization', title: 'CTA 2024-001234 - Sotorasib + Panitumumab', status: 'approved', submissionDate: '2023-10-15', approvalDate: '2024-01-20', expiryDate: '2027-01-20', authority: 'EMA', referenceNumber: 'CTA-2024-001234', notes: 'Approved for EU sites' },
      { trialId: 4, documentType: 'DSMB Charter', title: 'DSMB Charter - Olaparib + Bevacizumab', status: 'approved', submissionDate: '2024-01-15', approvalDate: '2024-02-28', authority: 'Independent DSMB', referenceNumber: 'DSMB-2024-004', notes: 'Interim analysis planned at 50% events' },
      { trialId: 5, documentType: 'Informed Consent', title: 'ICF v2.0 - Pembrolizumab + Lenvatinib', status: 'approved', submissionDate: '2024-03-01', approvalDate: '2024-04-15', authority: 'Central IRB', referenceNumber: 'ICF-2024-005', notes: 'Updated for new safety information' },
      { trialId: 6, documentType: 'IND Safety Report', title: 'IND Safety Report - Grade 4 Neutropenia', status: 'submitted', submissionDate: '2024-09-25', authority: 'FDA', referenceNumber: 'ISR-2024-006-001', notes: '15-day safety report submitted' },
      { trialId: 7, documentType: 'IRB Amendment', title: 'Amendment 2 - Dose Modification Schedule', status: 'approved', submissionDate: '2024-04-01', approvalDate: '2024-05-10', authority: 'Central IRB', referenceNumber: 'IRB-AMD-2024-007', notes: 'Talazoparib dose reduced to 0.5mg' },
      { trialId: 8, documentType: 'FDA Breakthrough Designation', title: 'BTD - Gilteritinib + Azacitidine in AML', status: 'approved', submissionDate: '2024-01-10', approvalDate: '2024-03-05', authority: 'FDA', referenceNumber: 'BTD-2024-008', notes: 'Breakthrough therapy designation granted' },
      { trialId: 9, documentType: 'Clinical Study Report', title: 'Interim CSR - Phase II Data', status: 'draft', submissionDate: '2024-10-01', authority: 'FDA', referenceNumber: 'CSR-INT-2024-009', notes: 'Interim analysis report in preparation' },
      { trialId: 10, documentType: 'IRB Approval', title: 'IRB Approval - SG + Pembro TNBC', status: 'approved', submissionDate: '2024-02-15', approvalDate: '2024-04-01', expiryDate: '2025-04-01', authority: 'Central IRB', referenceNumber: 'IRB-2024-010', notes: 'Initial approval with annual review' },
      { trialId: 11, documentType: 'PMDA Approval', title: 'PMDA Clinical Trial Notification', status: 'approved', submissionDate: '2023-11-15', approvalDate: '2024-01-10', authority: 'PMDA (Japan)', referenceNumber: 'CTN-2024-011', notes: 'Approved for Japan sites' },
      { trialId: 12, documentType: 'IND Application', title: 'IND 150789 - TMZ + TTFields + Pembro', status: 'approved', submissionDate: '2024-02-01', approvalDate: '2024-04-20', expiryDate: '2027-04-20', authority: 'FDA', referenceNumber: 'IND-150789', notes: 'Novel combination approved' },
      { trialId: 14, documentType: 'EMA Authorization', title: 'CTA - Dostarlimab + Carboplatin in EC', status: 'pending', submissionDate: '2024-05-01', authority: 'EMA', referenceNumber: 'CTA-2024-014', notes: 'Awaiting EMA authorization for EU expansion' },
      { trialId: 15, documentType: 'Health Canada Approval', title: 'CTA - Erdafitinib + Cetrelimab', status: 'approved', submissionDate: '2024-01-20', approvalDate: '2024-03-30', authority: 'Health Canada', referenceNumber: 'HC-CTA-2024-015', notes: 'Approved for Canadian sites' },
    ]);

    // Notifications (15+)
    await Notification.bulkCreate([
      { userId: 1, title: 'New Patient Match Found', message: 'Patient James Wilson (EGFR L858R+) matched with NCT-2024-001 at 92.5% confidence', type: 'match', priority: 'high', isRead: false, actionUrl: '/matches', category: 'matching' },
      { userId: 1, title: 'Enrollment Milestone', message: 'NCT-2024-004 has reached 50% enrollment target (210/400 patients)', type: 'enrollment', priority: 'normal', isRead: false, actionUrl: '/enrollments', category: 'enrollment' },
      { userId: 2, title: 'Adverse Event Alert', message: 'Grade 3 neutropenia reported for Patient Susan Brown in NCT-2024-006', type: 'safety', priority: 'urgent', isRead: false, actionUrl: '/adverse-events', category: 'safety' },
      { userId: 1, title: 'Protocol Amendment', message: 'Protocol PROTO-2024-007 Amendment 2 approved - dose modification for talazoparib', type: 'regulatory', priority: 'high', isRead: true, actionUrl: '/protocols', category: 'regulatory' },
      { userId: 2, title: 'IRB Renewal Due', message: 'IRB approval for NCT-2024-001 expires in 30 days. Renewal submission needed.', type: 'compliance', priority: 'high', isRead: false, actionUrl: '/regulatory', category: 'regulatory' },
      { userId: 1, title: 'Screening Failure', message: 'Patient Robert Thompson failed screening for NCT-2024-003 (KRAS variant mismatch)', type: 'enrollment', priority: 'normal', isRead: true, actionUrl: '/enrollments', category: 'enrollment' },
      { userId: 3, title: 'New Biomarker Results', message: 'Updated biomarker results available for Patient Patricia Harris - PD-L1 CPS: 70', type: 'biomarker', priority: 'normal', isRead: false, actionUrl: '/biomarkers', category: 'clinical' },
      { userId: 1, title: 'Drug Interaction Warning', message: 'Potential high-severity interaction detected: Trastuzumab + Zolbetuximab (cardiotoxicity risk)', type: 'safety', priority: 'urgent', isRead: false, actionUrl: '/drug-interactions', category: 'safety' },
      { userId: 2, title: 'Trial Status Update', message: 'NCT-2024-011 enrollment now at 267/480 (55.6%) - ahead of schedule', type: 'enrollment', priority: 'normal', isRead: false, actionUrl: '/trials', category: 'enrollment' },
      { userId: 3, title: 'Report Generated', message: 'Monthly enrollment summary report generated for all active trials', type: 'report', priority: 'low', isRead: false, actionUrl: '/reports', category: 'administrative' },
      { userId: 1, title: 'Breakthrough Designation', message: 'FDA granted Breakthrough Therapy Designation for NCT-2024-008 (Gilteritinib + Azacitidine)', type: 'regulatory', priority: 'high', isRead: true, actionUrl: '/regulatory', category: 'regulatory' },
      { userId: 2, title: 'Patient Withdrawal', message: 'Patient William Lee withdrew consent from NCT-2024-009 due to travel distance', type: 'enrollment', priority: 'normal', isRead: true, actionUrl: '/enrollments', category: 'enrollment' },
      { userId: 1, title: 'Safety Signal Detected', message: 'AI analysis detected potential ILD signal in NCT-2024-002 - review recommended', type: 'safety', priority: 'urgent', isRead: false, actionUrl: '/adverse-events', category: 'safety' },
      { userId: 3, title: 'Site Performance Alert', message: 'Moffitt Cancer Center enrollment rate below target - 3 patients in 60 days', type: 'site', priority: 'normal', isRead: false, actionUrl: '/sites', category: 'operations' },
      { userId: 1, title: 'Outcome Prediction Updated', message: 'AI model updated outcome predictions for NCT-2024-001 based on interim data', type: 'prediction', priority: 'normal', isRead: false, actionUrl: '/outcomes', category: 'analytics' },
    ]);

    // Reports (15+)
    await Report.bulkCreate([
      { title: 'Monthly Enrollment Summary - October 2024', type: 'enrollment', description: 'Comprehensive monthly enrollment report across all active trials', parameters: '{"month": "2024-10", "trials": "all"}', generatedBy: 'Dr. Sarah Johnson', status: 'generated', data: '{"totalEnrolled": 45, "totalScreened": 62, "screenFailRate": "27.4%"}', format: 'pdf' },
      { title: 'Safety Overview Report - Q3 2024', type: 'safety', description: 'Quarterly safety report summarizing all adverse events', parameters: '{"quarter": "Q3-2024"}', generatedBy: 'Dr. Michael Chen', status: 'generated', data: '{"totalAEs": 89, "seriousAEs": 12, "relatedAEs": 67}', format: 'pdf' },
      { title: 'NCT-2024-001 Interim Analysis', type: 'interim', description: 'Interim efficacy and safety analysis at 40% information fraction', parameters: '{"trialId": 1, "cutoffDate": "2024-10-31"}', generatedBy: 'Biostatistics Team', status: 'generated', data: '{"PFS_HR": 0.68, "ORR": "42%", "medianPFS": "12.3 months"}', format: 'pdf' },
      { title: 'Site Performance Dashboard - All Sites', type: 'performance', description: 'Site-by-site enrollment and performance metrics', parameters: '{"period": "2024-Q3"}', generatedBy: 'Emily Davis', status: 'generated', data: '{"topSite": "MD Anderson", "enrollmentRate": "4.2 pts/month"}', format: 'excel' },
      { title: 'Biomarker Correlation Analysis', type: 'biomarker', description: 'Analysis of biomarker prevalence and correlation with outcomes', parameters: '{"biomarkers": ["EGFR", "PD-L1", "HER2", "BRCA"]}', generatedBy: 'Dr. Michael Chen', status: 'generated', data: '{"EGFR_prevalence": "15%", "PD-L1_high": "32%", "correlation": "moderate"}', format: 'pdf' },
      { title: 'Regulatory Compliance Status Report', type: 'compliance', description: 'Current status of all regulatory documents and upcoming deadlines', parameters: '{"asOfDate": "2024-11-01"}', generatedBy: 'Regulatory Affairs', status: 'generated', data: '{"totalDocs": 45, "expiringSoon": 3, "pendingApprovals": 5}', format: 'pdf' },
      { title: 'Drug Interaction Summary Report', type: 'drug-interaction', description: 'Summary of all identified drug interactions across trials', parameters: '{"severity": "all"}', generatedBy: 'Clinical Pharmacology', status: 'generated', data: '{"totalInteractions": 15, "highSeverity": 2, "moderate": 8}', format: 'pdf' },
      { title: 'Patient Matching Accuracy Report', type: 'matching', description: 'AI matching algorithm performance and accuracy metrics', parameters: '{"period": "2024-H2"}', generatedBy: 'Data Science Team', status: 'generated', data: '{"accuracy": "89%", "precision": "91%", "recall": "85%"}', format: 'pdf' },
      { title: 'NCT-2024-004 Enrollment Projection', type: 'projection', description: 'Enrollment timeline projection based on current rates', parameters: '{"trialId": 4}', generatedBy: 'Emily Davis', status: 'generated', data: '{"projectedCompletion": "2026-08-15", "monthlyRate": 18}', format: 'pdf' },
      { title: 'Adverse Event Causality Assessment', type: 'causality', description: 'AI-assisted causality assessment for all open adverse events', parameters: '{"status": "open"}', generatedBy: 'AI Safety System', status: 'generated', data: '{"totalOpen": 8, "probable": 6, "possible": 2}', format: 'pdf' },
      { title: 'Multi-Trial Portfolio Overview', type: 'portfolio', description: 'Executive summary of all active clinical trials in portfolio', parameters: '{"status": "active"}', generatedBy: 'Dr. Sarah Johnson', status: 'generated', data: '{"activeTrials": 16, "totalPatients": 2100, "avgEnrollment": "58%"}', format: 'pdf' },
      { title: 'Screen Failure Analysis Report', type: 'screening', description: 'Analysis of screening failure reasons and rates by trial', parameters: '{"period": "2024"}', generatedBy: 'Clinical Operations', status: 'generated', data: '{"overallRate": "25%", "topReason": "Biomarker mismatch"}', format: 'excel' },
      { title: 'Cost per Patient Enrollment Analysis', type: 'financial', description: 'Financial analysis of enrollment costs across sites and trials', parameters: '{"year": "2024"}', generatedBy: 'Finance Team', status: 'generated', data: '{"avgCost": "$32,450", "rangeLow": "$18,000", "rangeHigh": "$55,000"}', format: 'excel' },
      { title: 'Protocol Deviation Summary', type: 'deviation', description: 'Summary of all protocol deviations across active trials', parameters: '{"period": "2024-Q3"}', generatedBy: 'Quality Assurance', status: 'generated', data: '{"totalDeviations": 23, "major": 3, "minor": 20}', format: 'pdf' },
      { title: 'AI Model Performance Dashboard', type: 'ai-performance', description: 'Performance metrics of AI matching and prediction models', parameters: '{"models": ["matching", "screening", "outcome"]}', generatedBy: 'Data Science Team', status: 'generated', data: '{"matchingF1": 0.88, "screeningAUC": 0.92, "outcomeR2": 0.74}', format: 'pdf' },
    ]);

    // Eligibility Criteria (15+)
    await Eligibility.bulkCreate([
      { trialId: 1, criteriaType: 'Molecular', category: 'Biomarker', description: 'EGFR activating mutation (exon 19 deletion or L858R) confirmed by validated test', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All', biomarkerRequirement: 'EGFR mutation positive' },
      { trialId: 1, criteriaType: 'Clinical', category: 'Disease Stage', description: 'Stage IIIB or IV non-small cell lung cancer not amenable to curative surgery or radiation', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All' },
      { trialId: 2, criteriaType: 'Molecular', category: 'Biomarker', description: 'HER2-positive (IHC 3+ or ISH amplified) confirmed by central lab', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All', biomarkerRequirement: 'HER2 positive (IHC 3+ or FISH+)' },
      { trialId: 3, criteriaType: 'Molecular', category: 'Biomarker', description: 'KRAS G12C mutation confirmed by validated NGS assay', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All', biomarkerRequirement: 'KRAS G12C mutation' },
      { trialId: 4, criteriaType: 'Molecular', category: 'Biomarker', description: 'Germline or somatic BRCA1 or BRCA2 pathogenic variant', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'Female', biomarkerRequirement: 'BRCA1/2 pathogenic variant' },
      { trialId: 5, criteriaType: 'Molecular', category: 'Biomarker', description: 'BRAF V600E or V600K mutation confirmed by validated assay', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All', biomarkerRequirement: 'BRAF V600 mutation' },
      { trialId: 1, criteriaType: 'Clinical', category: 'Performance Status', description: 'ECOG Performance Status 0-1', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All' },
      { trialId: 1, criteriaType: 'Clinical', category: 'Exclusion', description: 'Prior treatment with 3rd generation EGFR TKI', isInclusion: false, priority: 'required', ageMin: null, ageMax: null, gender: 'All' },
      { trialId: 6, criteriaType: 'Clinical', category: 'Treatment History', description: 'No prior systemic therapy for metastatic pancreatic cancer', isInclusion: true, priority: 'required', ageMin: 18, ageMax: 80, gender: 'All' },
      { trialId: 7, criteriaType: 'Molecular', category: 'Biomarker', description: 'BRCA1/2 or ATM mutation confirmed by tissue or blood NGS', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'Male', biomarkerRequirement: 'HRR gene mutation' },
      { trialId: 8, criteriaType: 'Molecular', category: 'Biomarker', description: 'FLT3-ITD or FLT3-TKD mutation confirmed', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All', biomarkerRequirement: 'FLT3 mutation' },
      { trialId: 10, criteriaType: 'Molecular', category: 'Biomarker', description: 'Triple-negative breast cancer (ER-, PR-, HER2-) with PD-L1 CPS >= 10', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All', biomarkerRequirement: 'TNBC, PD-L1 CPS >= 10' },
      { trialId: 12, criteriaType: 'Clinical', category: 'Disease', description: 'Newly diagnosed glioblastoma with MGMT promoter methylation', isInclusion: true, priority: 'required', ageMin: 18, ageMax: 75, gender: 'All', biomarkerRequirement: 'MGMT methylated' },
      { trialId: 14, criteriaType: 'Molecular', category: 'Biomarker', description: 'MSI-High or dMMR endometrial carcinoma confirmed by IHC or PCR', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'Female', biomarkerRequirement: 'MSI-H or dMMR' },
      { trialId: 15, criteriaType: 'Molecular', category: 'Biomarker', description: 'FGFR2 or FGFR3 alteration (mutation or fusion) confirmed', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All', biomarkerRequirement: 'FGFR2/3 alteration' },
      { trialId: 16, criteriaType: 'Molecular', category: 'Biomarker', description: 'Claudin 18.2 positive (IHC 2+ in >= 75% of cells), HER2 negative', isInclusion: true, priority: 'required', ageMin: 18, ageMax: null, gender: 'All', biomarkerRequirement: 'CLDN18.2+, HER2-' },
    ]);

    // Outcomes (15+)
    await Outcome.bulkCreate([
      { trialId: 1, patientId: 1, outcomeType: 'efficacy', endpoint: 'Progression-Free Survival', value: '14.2', unit: 'months', assessmentDate: '2024-10-15', status: 'ongoing', prediction: 'Favorable response predicted based on EGFR sensitivity', confidence: 0.85, notes: 'Partial response at week 12 assessment' },
      { trialId: 2, patientId: 2, outcomeType: 'efficacy', endpoint: 'Objective Response Rate', value: 'Partial Response', unit: '', assessmentDate: '2024-10-01', status: 'confirmed', prediction: 'Sustained response expected', confidence: 0.78, notes: '42% tumor reduction from baseline' },
      { trialId: 4, patientId: 4, outcomeType: 'efficacy', endpoint: 'Progression-Free Survival', value: '18.5', unit: 'months', assessmentDate: '2024-11-01', status: 'ongoing', prediction: 'Excellent prognosis with PARP + anti-VEGF', confidence: 0.88, notes: 'Complete response in CA-125' },
      { trialId: 5, patientId: 5, outcomeType: 'efficacy', endpoint: 'Objective Response Rate', value: 'Complete Response', unit: '', assessmentDate: '2024-10-20', status: 'confirmed', prediction: 'Durable response predicted', confidence: 0.82, notes: 'Complete metabolic response on PET' },
      { trialId: 6, patientId: 6, outcomeType: 'efficacy', endpoint: 'Overall Survival', value: '8.5', unit: 'months', assessmentDate: '2024-11-10', status: 'ongoing', prediction: 'Moderate benefit expected', confidence: 0.65, notes: 'Stable disease at latest assessment' },
      { trialId: 7, patientId: 7, outcomeType: 'efficacy', endpoint: 'PSA Response', value: '-65', unit: '% change', assessmentDate: '2024-11-05', status: 'confirmed', prediction: 'Good PSA response, rPFS benefit likely', confidence: 0.79, notes: '65% PSA decline from baseline' },
      { trialId: 8, patientId: 8, outcomeType: 'efficacy', endpoint: 'Complete Remission', value: 'CR', unit: '', assessmentDate: '2024-10-25', status: 'confirmed', prediction: 'High chance of sustained remission', confidence: 0.83, notes: 'MRD negative by flow cytometry' },
      { trialId: 1, patientId: 1, outcomeType: 'safety', endpoint: 'Overall Safety', value: 'Manageable', unit: '', assessmentDate: '2024-10-15', status: 'ongoing', prediction: 'Continued tolerability expected', confidence: 0.9, notes: 'Grade 1-2 AEs only, well-tolerated' },
      { trialId: 11, patientId: 11, outcomeType: 'efficacy', endpoint: 'Objective Response Rate', value: 'Stable Disease', unit: '', assessmentDate: '2024-11-10', status: 'confirmed', prediction: 'Disease control maintained', confidence: 0.72, notes: 'AFP declining, stable by RECIST' },
      { trialId: 12, patientId: 12, outcomeType: 'efficacy', endpoint: 'Overall Survival', value: '12+', unit: 'months', assessmentDate: '2024-11-01', status: 'ongoing', prediction: 'Above median OS for GBM', confidence: 0.76, notes: 'Stable MRI, no progression' },
      { trialId: 14, patientId: 14, outcomeType: 'efficacy', endpoint: 'Objective Response Rate', value: 'Partial Response', unit: '', assessmentDate: '2024-11-15', status: 'confirmed', prediction: 'Deep response likely in MSI-H', confidence: 0.87, notes: '55% tumor reduction, near CR' },
      { trialId: 2, patientId: 2, outcomeType: 'quality_of_life', endpoint: 'EORTC QLQ-C30', value: '72', unit: 'score', assessmentDate: '2024-10-01', status: 'confirmed', prediction: 'QoL maintained during treatment', confidence: 0.8, notes: 'Stable QoL from baseline' },
      { trialId: 5, patientId: 5, outcomeType: 'biomarker', endpoint: 'ctDNA Clearance', value: 'Cleared', unit: '', assessmentDate: '2024-10-20', status: 'confirmed', prediction: 'Molecular response correlates with imaging', confidence: 0.91, notes: 'ctDNA undetectable at week 16' },
      { trialId: 8, patientId: 8, outcomeType: 'biomarker', endpoint: 'MRD by NGS', value: 'Negative', unit: '', assessmentDate: '2024-10-25', status: 'confirmed', prediction: 'Deep molecular response, favorable prognosis', confidence: 0.85, notes: 'MRD negative at 10^-5 sensitivity' },
      { trialId: 10, patientId: 10, outcomeType: 'efficacy', endpoint: 'Objective Response Rate', value: 'Pending', unit: '', assessmentDate: '2024-11-20', status: 'pending', prediction: 'Response assessment pending first scan', confidence: 0.0, notes: 'First assessment scan scheduled' },
    ]);

    console.log('Seed data inserted successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();
